# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 565)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 761, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.Video_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.initPixelLabel(self.Video_1, "Video_1")
        self.gridLayout.addWidget(self.Video_1, 1, 0, 1, 1)

        self.Image_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.initPixelLabel(self.Image_1, "Image_1")
        self.gridLayout.addWidget(self.Image_1, 1, 1, 1, 1)

        self.snapshot_button = QtWidgets.QPushButton(Form)
        self.snapshot_button.setGeometry(QtCore.QRect(670, 510, 75, 23))
        self.snapshot_button.setObjectName("pushButton")

        self.text_video_1 = QtWidgets.QLabel(Form)
        self.text_video_1.setGeometry(QtCore.QRect(190, 20, 54, 12))
        self.text_video_1.setObjectName("text_video_1")
        self.text_video_1.setText("摄像头")

        self.text_image_1 = QtWidgets.QLabel(Form)
        self.text_image_1.setGeometry(QtCore.QRect(580, 20, 54, 12))
        self.text_image_1.setObjectName("text_image_1")
        self.text_image_1.setText("快照")

        self.detect_button_1 = QtWidgets.QPushButton(Form)
        self.detect_button_1.setGeometry(QtCore.QRect(570, 510, 75, 23))
        self.detect_button_1.setObjectName("detect_button_1")

        self.toggle_button_1 = QtWidgets.QPushButton(Form)
        self.toggle_button_1.setObjectName("toggle_button_1")
        self.toggle_button_1.setGeometry(QtCore.QRect(170, 280, 75, 23))

        self.gridLayoutWidget_test = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_test.setObjectName("gridLayoutWidget_2")
        self.gridLayoutWidget_test.setGeometry(QtCore.QRect(20, 310, 381, 231))
        self.gridLayout_test = QtWidgets.QGridLayout(self.gridLayoutWidget_test)
        self.gridLayout_test.setObjectName("gridLayout_2")
        self.gridLayout_test.setContentsMargins(0, 0, 0, 0)
        self.Image_test = QtWidgets.QLabel(self.gridLayoutWidget_test)
        self.Image_test.setFixedSize(QtCore.QSize(350, 200))
        self.Image_test.setAutoFillBackground(True)
        self.Image_test.setText("")
        self.Image_test.setScaledContents(True)
        self.Image_test.setObjectName("Image_test")

        self.gridLayout_test.addWidget(self.Image_test, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def initPixelLabel(self, label, name):
        label.setFixedSize(QtCore.QSize(350, 200))
        label.setAutoFillBackground(True)
        label.setText("")
        label.setScaledContents(True)
        label.setObjectName(name)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "国网项目 demo"))
        self.snapshot_button.setText(_translate("Form", "保存快照"))
        self.detect_button_1.setText(_translate("Form", "开始检测"))
        self.toggle_button_1.setText(_translate("Form", "关闭摄像头"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
